## Numpy
Seri belajar Numpy
pertemuan ke-4

In [1]:
# belajar numpy
# hal yang pertama dilakukan adalah menginstall numpy
# !pip install numpy

In [2]:
# setelah itu kita import numpy
import numpy as np

<p>numpy adalah library python yang digunakan untuk melakukan perhitungan matematika<br>
numpy juga memiliki fungsi operasi yang sangat cepat, sehingga sangat cocok untuk digunakan dalam machine learning</p>

<i>alasan menggunakan numpy adalah karena numpy lebih cepat dari pada list dan sebuah array numpy menggunakan lebih sedikit memori daripada list </i>


In [3]:
# salah satu cara menginisialisasi array adalah dari nested list
a = np.array([[1,2,3],[4,5,6]]) # ini adalah cara menginisialisasi array 2 dimensi
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
# membuat array 1 dimensi
b = np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [5]:
# membuat array 3 dimensi
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [6]:
# tipe data array harus sama semua tidak boleh campuran

In [7]:
# membuat array zeros
array_zeros = np.zeros((3,4))
print(array_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# membuat array ones
array_ones = np.ones((3,4))
print(array_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# kegunaan dari array zeros dan ones adalah untuk membuat array dengan nilai awal 0 atau 1

In [10]:
# membuat array dengan nilai empty
array_empty = np.empty((3,4))
print(array_empty)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
# kegunaan dari array empty adalah untuk 
# membuat array dengan nilai awal random dan tergantung dari memory yang tersedia.

In [12]:
# membuat array menggunakan arrange
array_arange = np.arange(10,25,2) # 10 adalah nilai awal, 25 adalah nilai akhir, 2 adalah step
print(array_arange) # fungsi range ini adalah untuk membuat array dengan nilai awal, nilai akhir, dan step

[10 12 14 16 18 20 22 24]


In [13]:
# add array
arr = np.array([1,2,3,4,5])
arr 

array([1, 2, 3, 4, 5])

In [14]:
# menambahkan array dengan fungsi append
np.append(arr, [6,7,8,9,10]) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# menghapus array dengan fungsi delete
np.delete(arr, [1,3]) # 1 dan 3 adalah index yang akan dihapus

array([1, 3, 5])

In [16]:
# mengurutkan array dengan fungsi sort
array_sort = np.array([2,1,4,3,5])
np.sort(array_sort)

array([1, 2, 3, 4, 5])

In [17]:
# shape dan size

In [18]:
# shape adalah untuk mengetahui dimensi dari array yang kita buat
# size adalah untuk mengetahui jumlah elemen dari array yang kita buat

In [19]:
# contoh shape
array_shape = np.array([[1,2,3],[4,5,6]])
array_shape.shape # hasilnya adalah (2,3) dimana 2 adalah jumlah baris dan 3 adalah jumlah kolom

(2, 3)

In [20]:
# contoh size
array_size = np.array([[1,2,3],[4,5,6]])
array_size.size # hasilnya adalah 6, yang dimana 6 adalah jumlah elemen dari array


6

In [21]:
# ndim adalah untuk mengetahui jumlah dimensi dari array yang kita buat
array_ndim = np.array([[1,2,3],[4,5,6]])
array_ndim.ndim # hasilnya adalah 2, yang dimana 2 adalah jumlah dimensi dari array

2

In [33]:
## reshaping array
# reshaping array adalah untuk mengubah bentuk dari array yang kita buat
# contoh reshaping array dari 2 dimensi menjadi 3 dimensi
array_reshape = np.array([[1,2,3],[4,5,6]])
array_reshape.reshape(3,1,2) # 3 adalah jumlah baris, 1 adalah jumlah kolom, 2 adalah jumlah elemen 
# hasilnya adalah array yang sudah di reshape menjadi 3 dimensi

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [34]:
# indexing dan slicing
# indexing adalah untuk mengambil nilai dari array yang kita buat

# contoh indexing
array_indexing = np.array([1,2,3,4,5,6,7,8,9,10])
array_indexing[0] # hasilnya adalah 1, yang dimana 1 adalah nilai dari index ke 0

1

In [35]:
array_indexing[0:3] # hasilnya adalah array([1,2,3]), yang dimana 1,2,3 adalah nilai dari index ke 0,1,2

array([1, 2, 3])

In [36]:
array_indexing[-1] # hasilnya adalah 10, yang dimana 10 adalah nilai dari index ke -1

10

In [37]:
array_indexing[array_indexing > 5] # hasilnya adalah array([6,7,8,9,10]), yang dimana 6,7,8,9,10 adalah nilai dari index yang lebih dari 5

array([ 6,  7,  8,  9, 10])

In [38]:
array_indexing[array_indexing % 2 == 0] # hasilnya adalah array([2,4,6,8,10]), yang dimana 2,4,6,8,10 adalah nilai dari index yang habis dibagi 2

array([ 2,  4,  6,  8, 10])

In [40]:
array_indexing[(array_indexing > 5) & (array_indexing % 2 == 0)]

array([ 6,  8, 10])

In [41]:
array_indexing[:3]

array([1, 2, 3])

In [42]:
array_indexing[:4]

array([1, 2, 3, 4])

In [45]:
# np vstack dan hstack
# vstack adalah untuk menggabungkan array secara vertikal (menumpuk)
# hstack adalah untuk menggabungkan array secara horizontal (menumpuk)
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [47]:
# contoh vstack
np.vstack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# contoh hstack
np.hstack((array1,array2))

array([1, 2, 3, 4, 5, 6])

In [48]:
#split array
# split array adalah untuk membagi array menjadi beberapa bagian
arrsplit = np.array([
    [1,2,3,4,5,6,7,8,9,10,11,12]
    ,[13,14,15,16,17,18,19,20,21,22,23,24]
])

In [49]:
# contoh split array
np.split(arrsplit,2) # 2 adalah jumlah array yang akan dibagi

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [50]:
# contoh hspli array
np.hsplit(arrsplit,3) # 3 adalah jumlah array yang akan dibagi secara horizontal

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [53]:
# contoh vsplit array
np.vsplit(arrsplit,2) # 2 adalah jumlah array yang akan dibagi secara vertikal

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [54]:
# copy & view
# copy adalah untuk membuat copy dari array yang kita buat
# contoh copy
array_copy = np.array([1,2,3,4,5])
array_copy2 = array_copy.copy()

In [55]:
array_copy2

array([1, 2, 3, 4, 5])

In [56]:
# contoh view
# ketika kita membuat view dari array, maka array yang kita buat akan berubah jika array yang kita buat viewnya berubah
array_view = np.array([1,2,3,4,5])
array_view2 = array_view.view()

In [57]:
array_view2

array([1, 2, 3, 4, 5])

In [60]:
array_view2*2

array([ 2,  4,  6,  8, 10])

In [61]:
array_view

array([1, 2, 3, 4, 5])

In [62]:
# perbedaan copy dan view adalah ketika kita membuat copy dari array, maka array yang kita buat tidak akan berubah jika array yang kita buat copynya berubah sedangkan ketika kita membuat view dari array, maka array yang kita buat akan berubah jika array yang kita buat viewnya berubah

In [63]:
## basic array operation
# basic array operation terdiri dari 4 yaitu:
# 1. array aritmatika
# 2. array perbandingan
# 3. array logika
# 4. array trigonometri

In [64]:
# array aritmatika
# array aritmatika terdiri dari 4 yaitu:
# 1. penjumlahan
# 2. pengurangan
# 3. perkalian
# 4. pembagian

# contoh penjumlahan
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

array1 + array2

array([ 7,  9, 11, 13, 15])

In [65]:
# contoh pengurangan
array1 - array2

array([-5, -5, -5, -5, -5])

In [67]:
# contoh perkalian
array1 * array2


array([ 6, 14, 24, 36, 50])

In [68]:
# contoh pembagian
array1 / array2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [69]:
# array perbandingan
# array perbandingan terdiri dari 6 yaitu:
# 1. sama dengan
# 2. tidak sama dengan
# 3. lebih besar dari
# 4. lebih kecil dari
# 5. lebih besar dari sama dengan
# 6. lebih kecil dari sama dengan

# contoh sama dengan
array1 == array2

array([False, False, False, False, False])

In [70]:
# contoh tidak sama dengan
array1 != array2

array([ True,  True,  True,  True,  True])

In [71]:
# contoh lebih besar dari
array1 > array2

array([False, False, False, False, False])

In [72]:
# contoh lebih kecil dari
array1 < array2

array([ True,  True,  True,  True,  True])

In [73]:
# contoh lebih besar dari sama dengan
array1 >= array2

array([False, False, False, False, False])

In [74]:
# contoh lebih kecil dari sama dengan
array1 <= array2

array([ True,  True,  True,  True,  True])

In [75]:
# array logika
# array logika terdiri dari 3 yaitu:
# 1. and
# 2. or
# 3. not

# contoh and
array1 & array2

array([0, 2, 0, 0, 0])

In [76]:
# contoh or
array1 | array2

array([ 7,  7, 11, 13, 15])

In [77]:
# contoh not
# not adalah untuk membalikkan nilai dari array yang kita buat
~array1 # hasilnya adalah array([-2, -3, -4, -5, -6]) yang dimana -2, -3, -4, -5, -6 adalah nilai dari array1 yang sudah di not

array([-2, -3, -4, -5, -6])

In [101]:
# array trigonometri
# array trigonometri terdiri dari 6 yaitu:
# 1. sin
# 2. cos
# 3. tan
# 4. arcsin
# 5. arccos
# 6. arctan

# contoh sin
np.sin(array1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [98]:
# contoh cos
np.cos(array1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [99]:
# contoh tan
np.tan(array1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [100]:
# contoh arcsin
np.arcsin(array1)

C:\Users\hp\AppData\Local\Temp\ipykernel_17788\1684762461.py:2: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr_1)


array([1.57079633,        nan,        nan])

In [82]:
# contoh arccos
np.arccos(array1)

C:\Users\hp\AppData\Local\Temp\ipykernel_17788\1278818080.py:2: RuntimeWarning: invalid value encountered in arccos
  np.arccos(array1)


array([ 0., nan, nan, nan, nan])

In [83]:
# contoh arctan
np.arctan(array1)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077])

In [84]:
# array statistik
# array statistik terdiri dari 6 yaitu:
# 1. min
# 2. max
# 3. sum
# 4. mean
# 5. median
# 6. std

In [85]:
# contoh min
np.min(array1)

1

In [86]:
# contoh max
np.max(array1)

5

In [87]:
# contoh sum
np.sum(array1)

15

In [88]:
# contoh mean
np.mean(array1)

3.0

In [89]:
# contoh median
np.median(array1)

3.0

In [90]:
# contoh std
np.std(array1)

1.4142135623730951

In [102]:
# array linear algebra
# array linear algebra terdiri dari 2 yaitu:
# 1. dot
# 2. cross

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

In [103]:
# contoh dot
# dot adalah untuk mengalikan array secara matriks 

np.dot(arr_1,arr_2)

32

In [104]:
# contoh cross
# cross adalah untuk mengalikan array secara vektor

np.cross(arr_1,arr_2)

array([-3,  6, -3])

In [107]:
# Matrix

# np.zeros((3,3))
# np.ones((3,3))

np.random.random((3,3))



array([[0.75637411, 0.30979943, 0.25425255],
       [0.13513882, 0.4027445 , 0.1755626 ],
       [0.18489541, 0.94397261, 0.69698873]])